/**
 * App theme configuration. Served by GET /api/theme.
 * Change these values to customize the app appearance from the backend.
 */
export const THEME_CONFIG = {
  defaultColorScheme: "auto", // "light" | "dark" | "auto"
  brandColors: {
    primary: "#FF6B35",
    primaryDark: "#E55A28",
    secondary: "#004E89",
    secondaryLight: "#0066B3",
    accent: "#FFD23F",
    accentDark: "#E5BC38",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
  },
  light: {
    text: "#1A1A1A",
    textSecondary: "#6B7280",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7280",
    tabIconSelected: "#FF6B35",
    link: "#FF6B35",
    primary: "#FF6B35",
    primaryDark: "#E55A28",
    secondary: "#004E89",
    accent: "#FFD23F",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#F7F9FB",
    backgroundSecondary: "#EEF2F6",
    backgroundTertiary: "#E1E8ED",
    border: "#E1E8ED",
    cardBackground: "#FFFFFF",
    inputBackground: "#F7F9FB",
    overlay: "rgba(0, 0, 0, 0.5)",
  },
  dark: {
    text: "#ECEDEE",
    textSecondary: "#9BA1A6",
    buttonText: "#FFFFFF",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: "#FF8A5C",
    link: "#FF8A5C",
    primary: "#FF8A5C",
    primaryDark: "#FF6B35",
    secondary: "#3399CC",
    accent: "#FFD23F",
    success: "#34D399",
    warning: "#FBBF24",
    error: "#F87171",
    backgroundRoot: "#0F1419",
    backgroundDefault: "#1A1F26",
    backgroundSecondary: "#252B33",
    backgroundTertiary: "#303842",
    border: "#303842",
    cardBackground: "#1A1F26",
    inputBackground: "#252B33",
    overlay: "rgba(0, 0, 0, 0.7)",
  },
};
